baseurl = "/"
languageCode = "en-us"
title = "MVPS"

[params]
  description = "Long Beach Legends"

[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 1
[[menu.main]]
    name = "Drinks"
    url  = "/drinks"
    weight = 2
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 3
[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 4
